spring.application.name=auth-api

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=auth_user
spring.datasource.password=auth_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

logging.level.root=INFO
logging.level.com.dario.enterprise.authapi=DEBUG

#APPENA MODIFICO JWTSERVICE SCOMMENTA
jwt.secret=k3J9sdf8JH23kjsdf89JKSDF98jsdf98JKSDF98jsdf98JKSDF==
jwt.expiration=3600000
